"$schema": http://json-schema.org/draft-07/schema#
title: Schema for unity catalog metadata files
type: object
properties:
  description:
    type: string
  business_owner:
    type: string
  data_steward:
    type: string
  technical_owner:
    type: string
  PII:
    type: boolean
  FINANCIAL:
    type: boolean
  SOX:
    type: boolean
  tags:
    type: array    
    items:
      oneOf:
        - type: string
        - type: object
          minProperties: 1
          maxProperties: 1
          additionalProperties:
            type: string

  columns:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
          tags:
            type: array
            items:
              oneOf:
                - type: string
                - type: object
                  minProperties: 1
                  maxProperties: 1
                  additionalProperties:
                    type: string
      required:
        - name
        - description
required:
  - description
  - business_owner
  - data_steward
  - technical_owner
  - PII
  - FINANCIAL
  - SOX
