name: Validate Unity Catalog Metadata Files
description: Validates YAML metadata files using yamllint and schema validation
inputs:
  file-list:
    description: "List of files to validate separated by blank spaces"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create temporary yamllint config
      run: |
        cat <<-EOF > .yamllint
        extends: default

        rules:
          document-start: disable
        EOF
      shell: bash

    - name: Run yamllint
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: ${{ inputs.file-list }}
        yamllint_strict: true

    - name: Prepare changed files with newlines
      id: prepared-changed-files
      run: |
        {
          echo 'files_changed<<EOF'
          echo "${{ inputs.file-list }}" | tr ' ' '\n'
          echo 'EOF'
        } >> $GITHUB_OUTPUT
        cp ${{ github.action_path }}/schema.yml ./uc-metadata-schema.yml
      shell: bash

    - name: Validate schema
      uses: RomanosTrechlis/actions-validate-yaml@master
      with:
        schema: ./uc-metadata-schema.yml
        data: ${{ steps.prepared-changed-files.outputs.files_changed }}
