name: 'AWS Credentials Action'
description: 'Sets AWS credentials using OIDC and assumes an additional role'
inputs:
  role-to-assume:
    description: 'The AWS role to assume with OIDC'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  cicd-deployment-role:
    description: 'The CICD role to assume'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: 'composite'
  steps:
    - name: Get AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - name: Give execute permissions to aws-credentials.sh
      run: chmod +x mac87-git/templates-github-actions/.github/actions/aws-credentials-action-v1/aws-credentials.sh@main
      shell: bash
    - name: Run AWS credentials script
      run: mac87-git/templates-github-actions/.github/actions/aws-credentials-action-v1/aws-credentials.sh@main
      shell: bash
      env:
        INPUT_ROLE_TO_ASSUME: ${{ inputs.role-to-assume }}
        INPUT_AWS_REGION: ${{ inputs.aws-region }}
        INPUT_CICD_DEPLOYMENT_ROLE: ${{ inputs.cicd-deployment-role }}