name: Deploy Airflow DAGs
on:
  workflow_call:
    inputs:
      bucket-name:
        required: true
        type: string
      dir_name:
        required: false
        description: 'Name of the folder where the dags will live'
        type: string
        default: "${{github.event.repository.name}}"
      dags_subdirs:
        description: whitespace separated list of subdiretories to deploy
        required: true
        type: string
      dags_repository_folder:
        required: false
        type: string
        description: 'Path of the dags folder in the dags repository'
        default: dags
      enable_full_clean:
        description: 'Enable complete deletion of dir_name folder before deployment'
        required: false
        default: false
        type: boolean

    secrets:
      AWS_OIDC_ROLE:
        required: true
      CICD_DEPLOYMENT_ROLE:
        required: true

jobs:
  deploy-dags:
    name: 'Deploy DAGs to S3'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout head: ${{ github.event.pull_request.head.ref }}'
        uses: actions/checkout@v4

      - name: Configure AWS credentials and assume roles
        uses: mac87-git/templates-github-actions/.github/actions/aws-credentials-action-v1@main
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: 'us-east-1'
          cicd-deployment-role: ${{ secrets.CICD_DEPLOYMENT_ROLE }}

      - name: Clean bucket folder dags/${{ inputs.dir_name }} (runs only if enable_full_clean is true)
        if: ${{ inputs.enable_full_clean == true }}
        run: |
          echo "Removing content from s3://${{ inputs.bucket-name }}/dags/${{ inputs.dir_name }} folder"
          aws s3 rm s3://${{ inputs.bucket-name }}/dags/${{ inputs.dir_name }} --recursive

      - name: Copy DAGs
        id: copy-dags
        run: |
          for subdir in ${{ inputs.dags_subdirs }}; do
            echo "Syncing s3://${{ inputs.bucket-name }}/dags/${{ inputs.dir_name }}/$subdir folder"
            subdir_path="${{ inputs.dags_repository_folder }}/$subdir"
            aws s3 sync --delete $subdir_path s3://${{ inputs.bucket-name }}/dags/${{ inputs.dir_name }}/$subdir 
          done