name: Test DBT projects integrity
on:
  workflow_call:
    inputs:
      dbt_repository_folder:
        required: false
        type: string
        description: 'Path of the dbt projects folder in the repository'
        default: dbt
      dbt_projects_list:
        description: whitespace separated list of projects to deploy
        required: true
        type: string
      environment:
        description: 'Select the environment to deploy'
        required: true
        type: string
      python_version:
        description: 'Python version to use for parsing dbt projects'
        required: true
        type: string
      poetry_install_options:
        description: 'Optional parameters to pass to the poetry install command'
        required: false
        type: string 
  
jobs:
  test-dbt:
    name: 'Test dbt projects'
    runs-on: ubuntu-latest
    env:
      # cache_path should be absolute:
      DBT_CACHE_PATH: /tmp/dbt_cache
      DBT_TARGET_CACHE_GLOB: /tmp/dbt_cache/*/target
      DBT_REPOSITORY_FOLDER: ${{ inputs.dbt_repository_folder }}
      PYTHON_VERSION: ${{ inputs.python_version }}
      POETRY_INSTALL_OPTIONS: ${{ inputs.poetry_install_options }}
      ENVIRONMENT: ${{ inputs.environment }}
      DBT_ENV_SECRET_DBKS_DEV_TOKEN: mock
      DBT_ENV_SECRET_DBKS_PRD_TOKEN: mock
      DBT_ENV_SECRET_DBKS_BANKING_DEV_TOKEN: mock
      DBT_ENV_SECRET_DBKS_BANKING_PRD_TOKEN: mock
    steps:
      # BEGIN SETUP
      - name: 'Checkout head: ${{ github.event.pull_request.head.ref }}'
        uses: actions/checkout@v4

      - run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - run: poetry install ${{ env.POETRY_INSTALL_OPTIONS }}

      - name: Use DBT Cache Action
        uses: mac87-git/templates-github-actions/.github/actions/dbt-target-cache-v1@main
        with:
          dbt_projects_list: ${{ inputs.dbt_projects_list }}

      - name: Test full dbt projects
        run: |
          echo dbt_projects_list: ${{ inputs.dbt_projects_list }}
          for project in ${{ inputs.dbt_projects_list }}; do
            project_path="$DBT_REPOSITORY_FOLDER/$project"
            echo " ** Processing: $project_path **"
            if [[ -d $project_path && -f $project_path/profiles.yml && -f $project_path/dbt_project.yml ]]; then
              echo " ** Testing dbt project: $project_path **"
              export DBT_PROJECT_DIR=$project_path
              export DBT_PROFILES_DIR=$DBT_PROJECT_DIR
              export DBT_TARGET_PATH=$DBT_CACHE_PATH/$project/target
              poetry run dbt parse --target $ENVIRONMENT
              tree $project_path
            fi
          done