name: Deploy DBT projects
on:
  workflow_call:
    inputs:
      bucket-name:
        required: true
        type: string
      dbt_dir_dest:
        required: false
        description: 'Name of the folder where the dbt projects will live'
        type: string
        default: "${{github.event.repository.name}}_dbt_projects"
      dbt_repository_folder:
        required: false
        type: string
        description: 'Path of the dbt projects folder in the repository'
        default: dbt
      dbt_projects_list:
        description: whitespace separated list of projects to deploy
        required: true
        type: string
      environment:
        description: 'Select the environment to deploy'
        required: true
        type: string
      python_version:
        description: 'Python version to use for parsing dbt projects'
        required: true
        type: string
      poetry_install_options:
        description: 'Optional parameters to pass to the poetry install command'
        required: false
        type: string
      enable_full_clean:
        description: 'Enable complete deletion of dir_name folder before deployment'
        required: false
        default: false
        type: boolean

    secrets:
      AWS_OIDC_ROLE:
        required: true
      CICD_DEPLOYMENT_ROLE:
        required: true
  
jobs:

  deploy-dbt:
    name: 'Deploy DBT projects to S3'
    runs-on: ubuntu-latest
    env:
      # cache_path should be absolute:
      DBT_CACHE_PATH: /tmp/dbt_cache
      DBT_TARGET_CACHE_GLOB: /tmp/dbt_cache/*/target
      DBT_REPOSITORY_FOLDER: ${{ inputs.dbt_repository_folder }}
      PYTHON_VERSION: ${{ inputs.python_version }}
      POETRY_INSTALL_OPTIONS: ${{ inputs.poetry_install_options }}
      ENVIRONMENT: ${{ inputs.environment }}
      DBT_ENV_SECRET_DBKS_DEV_TOKEN: mock
      DBT_ENV_SECRET_DBKS_PRD_TOKEN: mock
      DBT_ENV_SECRET_DBKS_BANKING_DEV_TOKEN: mock
      DBT_ENV_SECRET_DBKS_BANKING_PRD_TOKEN: mock
    steps:
      - name: 'Checkout head: ${{ github.event.pull_request.head.ref }}'
        uses: actions/checkout@v4

      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: poetry install ${{ env.POETRY_INSTALL_OPTIONS }}

      - name: Use DBT Cache Action
        uses: mac87-git/templates-github-actions/.github/actions/dbt-target-cache-v1@main
        with:
          dbt_projects_list: ${{ inputs.dbt_projects_list }}

      - name: Compile dbt
        id: compile-dbt
        run: |
          for project in ${{ inputs.dbt_projects_list }}; do
            project_path="$DBT_REPOSITORY_FOLDER/$project"
            if [[ -d $project_path && -f $project_path/profiles.yml && -f $project_path/dbt_project.yml ]]; then
              echo " ** Testing and Compiling dbt project: $project_path **"
              export DBT_PROJECT_DIR=$project_path
              export DBT_PROFILES_DIR=$DBT_PROJECT_DIR
              # discard logs
              export DBT_LOG_PATH=/tmp/${project}_logs

              poetry run dbt deps
              poetry run dbt parse --target $ENVIRONMENT || (echo "::error:: Project $project is incompatible with other dev changes" && exit 1)
            fi                
          done

      - name: Configure AWS credentials and assume roles
        uses: mac87-git/templates-github-actions/.github/actions/aws-credentials-action-v1@main
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: 'us-east-1'
          cicd-deployment-role: ${{ secrets.CICD_DEPLOYMENT_ROLE }}

      - name: Clean bucket folder dags/${{ inputs.dbt_dir_dest }} (runs only if enable_full_clean is true)
        if: ${{ inputs.enable_full_clean == true }}
        run: |
          echo "Removing content from s3://${{ inputs.bucket-name }}/dags/${{ inputs.dbt_dir_dest }} folder"
          aws s3 rm s3://${{ inputs.bucket-name }}/dags/${{ inputs.dbt_dir_dest }} --recursive

      - name: Copy DBT projects
        id: copy-dbt-projects
        run: |
          for project in ${{ inputs.dbt_projects_list }}; do
            project_path="$DBT_REPOSITORY_FOLDER/$project"
            if [[ -d $project_path && -f $project_path/profiles.yml && -f $project_path/dbt_project.yml ]]; then
              echo "Syncing s3://${{ inputs.bucket-name }}/dags/${{ inputs.dbt_dir_dest }}/$project folder"
              aws s3 sync --delete $project_path s3://${{ inputs.bucket-name }}/dags/${{ inputs.dbt_dir_dest }}/$project
            fi                
          done