name: Test dbt projects integrity
on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
    paths:
      - 'dbt/core/**'
      - 'dbt/mac/**'

permissions:
  # From
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
  id-token: write
  contents: read

jobs:

  test-dbt:
    uses: ./.github/workflows/pipeline-test-dbt-v1.yml
    with:
      environment: ${{ github.event.pull_request.base.ref == 'develop' && 'dev' || (github.event.pull_request.base.ref == 'master' && 'prd' || 'dev') }}
      dbt_repository_folder: dbt
      dbt_projects_list: core mac
      python_version: 3.12
      poetry_install_options: ""

