name: Validating Unity Catalog Metadata Files

on:
  workflow_call:
    inputs:
      base_rev:
        description: branch or commit used as base for compare
        required: true
        type: string
      head_rev:
        description: branch or commit used as head for compare
        required: true
        type: string

permissions:
  contents: read # This is required for actions/checkout

jobs:
  
  changed-metadata-files:
    name: Get modified metadata files
    uses: mac87-git/templates-github-actions/.github/workflows/wf-get-changed-metadata-files.yml@main
    #uses: ClipMX/data-github-actions-templates/.github/workflows/wf-get-changed-metadata-files.yml@main
    with:
      base_rev: ${{ inputs.base_rev }}
      head_rev: ${{ inputs.head_rev }}

  validate-metadata-files:
    runs-on: ubuntu-latest
    needs: changed-metadata-files
    if: ${{ needs.changed-metadata-files.outputs.changed != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate metadata yml files
        uses: mac87-git/templates-github-actions/.github/actions/uc-metadata-validate-action@main
        # uses: ClipMX/data-github-actions-templates/.github/actions/uc-metadata-validate-action@main
        with:
          file-list: ${{ needs.changed-metadata-files.outputs.changed }}
