name: Test metadata files

on:
  workflow_call:
    inputs:
      base_rev:
        description: branch or commit used as base for compare
        required: true
        type: string
      head_rev:
        description: branch or commit used as head for compare
        required: true
        type: string

permissions:
  # From
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
  id-token: write
  contents: read

jobs:
  
  changed-files:
    name: Get changed files
    needs: fail-if-pull-request-is-draft
    # uses: ./.github/workflows/wf-get-changed-metadata-files.yml 
    uses: mac87-git/templates-github-actions/.github/workflows/wf-get-changed-metadata-files.yml@main
    with:
      base_rev: ${{ inputs.base_rev }}
      head_rev: ${{ inputs.head_rev }}

  validate-metadata:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.changed != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate metadata yml files
        uses: mac87-git/templates-github-actions/.github/actions/validate-uc-metadata-files@main
        with:
          changed: ${{ needs.changed-files.outputs.changed }}  
